FROM ubuntu
COPY cmd.sh /cmd.sh
LABEL vendor=Katacoda
LABEL com.katacoda.version=0.0.5
LABEL com.katacoda.build-date=2015-07-01T10:47:29Z
LABEL com.katacoda.private-msg=HelloWorld
LABEL com.katacoda.course=Docker
CMD ["sh", "-c", "/cmd.sh"]
