#
# I'm using the Awesome Compose exercises.
# This one is to sping up a PSQL server.
# I want to have a Grafana danshboard for the DB.
# Also I want to have system metrics.
#
# I added the Prometheus, Grafana and Netshoot containers.
#
# Sun 2022Dec04 18:35:39 PST
#
services:

#
# POSTGRES
#
  postgresPRIMARY:
    container_name: postgres-PRIMARY
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

#
# PGADMIN
#
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

#
# NETUTILS
#   
  netutils:
    image: nicolaka/netshoot
    hostname: netutils
    container_name: netutils
    restart: on-failure
    volumes:
      - "./:/hostdata"      
    command: ["sleep", "infinity"]

#
# PROMETHEUS
#    
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
#
# GRAFANA
#  
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
#
# postgres-exporter
#
# https://github.com/prometheus-community/postgres_exporter
#
  # postgresExporter:
  #   image: quay.io/prometheuscommunity/postgres-exporter
  #   container_name: postgres-exporter
    # environment:
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PW}
    #   - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    # ports:    
#
# UBUNTU
#      
  ubuntu2004:
    image: ubuntu:20.04
    container_name: u2004-1
    restart: on-failure
    command: ["sleep", "infinity"]    

#
# VOLUMES: P8s
#      
volumes:
# p8s
  prom_data:
