#
#  SystemD on FEDORA
# https://developers.redhat.com/blog/2014/05/05/running-systemd-within-docker-container
#
# -> docker pull registry.fedoraproject.org/f34/s2i-base
# bash-5.1#  yum -y update; yum clean all
# bash-5.1#  rpm -qa | grep systemd
# systemd-libs-248.10-1.fc34.x86_64
# rpm-plugin-systemd-inhibit-4.16.1.3-1.fc34.x86_64
# systemd-rpm-macros-248.10-1.fc34.noarch
# systemd-networkd-248.10-1.fc34.x86_64
# systemd-pam-248.10-1.fc34.x86_64
# systemd-248.10-1.fc34.x86_64
# bash-5.1#
# bash-5.1# which init
# /usr/sbin/init

services:

#
# FIRST - RedHat9
# Provides SystemD functionallity
#  
  f34-1:
    image: registry.fedoraproject.org/f34/s2i-base
    hostname: f34-1
    container_name: f34-1
    privileged: true
    entrypoint: ["/usr/sbin/init"]    
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 
