#
#  Compose ALL PURPOSE TESTING
#
#  RHEL9 DevEsp Image: https://hub.docker.com/repository/docker/dockio/rhel9-devesp/general
#  U2204 DevEsp Image: https://hub.docker.com/repository/docker/dockio/u2204-devesp/general
#
#  Date: Sat 2023Jul15 15:16:12 PDT - DevEsp images pushed to Docker Hub
#
services:

#
# RHEL 9 - WORKS
# Provides SystemD functionallity
# Add entrypoint.
# Comes with /usr/sbin/service
# Manage services: 
#    systemctl status ssh
#  
  rhel9test:
    image: dockio/rhel9-devesp:1.0
    hostname: rhel9test
    container_name: rhel9test
    privileged: true
    entrypoint: ["/usr/sbin/init"]    
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 

# U22 - WORKS
#  Add entrypoint.
#  Comes with /usr/sbin/service
#  Manage services: 
#     service ssh status
#     systemctl status ssh
#     
  ubuntu2204-devesp:
    image: dockio/u2204-devesp:1.0       
    hostname: ubuntu2204-devesp
    container_name: ubuntu2204-devesp
    privileged: true 
    entrypoint: ["/usr/sbin/init"]     
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 

# #
# # FIRST - Fedora
# # Provides SystemD functionallity
# #  
#   f34-1:
#     image: registry.fedoraproject.org/f34/s2i-base
#     hostname: f34-1
#     container_name: f34-1
#     privileged: true
#     entrypoint: ["/usr/sbin/init"]    
#     restart: on-failure
#     volumes:
#       - "./:/hostdata"    
#     command: ["sleep", "infinity"] 
