#
# First spin to test RHEL9 containers in docker compose.
# 
# This allows the use of SYSTEMD to manage services.
#
# Date: Fri 2023Jun30 23:07:06 PDT
#
# version: "2.13.0"

services:
#
# FIRST - RedHat9
# Provides SystemD functionallity
#  
  rhel9-1:
    image: registry.access.redhat.com/ubi9/ubi-init
    hostname: rhel9-1
    container_name: rhel9-1
    privileged: true
    entrypoint: ["/usr/sbin/init"]    
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 
