#Dockerfile based on the latest centos 7 image - non-provilegted user entry
FROM centos:latest
LABEL maintainer="devuser@example.com"

# This runs as root and will be part of the container image
RUN useradd -ms /bin/bash user1

ENTRYPOINT echo "This command will display a message from EVERY container that runs from it"

USER user1