#
# Start an UBUNTU environment.
# I'm using the Awesome Compose exercises.
# https://stackoverflow.com/questions/60260437/running-a-ubuntu-container-in-background-using-docker-compose
#
# There is no need to specify an entrypoint to keep the container alve
# as it is done with CentOS79.
#
# Date: Mon 2023Jan16 21:28:48 PST -- initial environment
#
services:

#
# NETUTILS
#   
  netutils:
    image: nicolaka/netshoot
    hostname: netutils
    container_name: netutils
    restart: on-failure
    volumes:
      - "./:/hostdata"      
    command: ["sleep", "infinity"]

#
# PRIMARY - Ubuntu
#  
  ubuntu2204-1:
    image: ubuntu:22.04
    hostname: server01
    container_name: u1
    privileged: true
    restart: on-failure
    volumes:
      - "./:/hostdata"      
    command: ["sleep", "infinity"]      

#
# SECONDARY - Ubuntu
#  
  ubuntu2204-2:
    image: ubuntu:22.04
    hostname: server02
    container_name: u2
    privileged: true   
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 

#
# THIRD - Ubuntu
#  
  ubuntu2204-3:
    image: ubuntu:22.04
    hostname: server03
    container_name: u3
    privileged: true   
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 
