#
# I'm using the Awesome Compose exercises.
# This one is to sping up a PSQL server.
# I want to have a Grafana danshboard for the DB.
# Also I want to have system metrics.
#
# I added the Prometheus, Grafana and Netshoot containers.
#
# Sun 2022Dec04 18:35:39 PST
#
services:

#
# POSTGRES VMs 
#
  postgresPRIMARY:
    container_name: postgres-PRIMARY
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5432:5432"
    restart: always

  postgresSECONDARY:
    container_name: postgres-SECONDARY
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - POSTGRES_DB=${POSTGRES_DB} #optional (specify default database instead of $POSTGRES_DB)
    ports:
      - "5433:5432"
    restart: always
#
# PGADMIN
#    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_MAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PW}
    ports:
      - "5050:80"
    restart: always

#
# NETUTILS
#
  netutils:
    image: nicolaka/netshoot
    container_name: netutils
    restart: on-failure
    command: ["sleep", "infinity"]

#
# To use as PSQL client
#
  ubuntu2004:
    image: ubuntu:20.04
    container_name: u2004-1
    restart: on-failure
    command: ["sleep", "infinity"]      

#
# VOLUMES:
#    
volumes:
# p8s
  prom_data:
