#
# DevESP teaching environment.
#
# In this config all containers can talk to each other on the given networks.
# But the ip address given in one network can be on the same range as the one
# given on another netwrok. I want all to be different VLANS.
#
# https://stackoverflow.com/questions/72216583/docker-compose-networking-priority-property-ignored
#
# Created: Sat 2023Jun10 16:53:59 PDT
#
# version: "2.13.0"

services:

#
# NETUTILS
#  
  netutils:
    image: nicolaka/netshoot
    networks:
      net1:
        priority: 10
        ipv4_address: "172.44.4.4"
      net2:
        priority: 0
      net3:
        priority: 0
    hostname: netutils
    container_name: netutils-devesp
    restart: on-failure
    volumes:
      - "./:/hostdata"         
    command: ["sleep", "infinity"]

#
# CentOS8 - FIRST
#  
  centos1:
    image: centos:8.4.2105
    networks:
      net1:
        priority: 10
        ipv4_address: "172.44.4.2"
      net2:
        priority: 0
      net3:
        priority: 0
    hostname: centos1
    container_name: centos1-devesp
    privileged: true
    entrypoint: ["/usr/sbin/init"]
    restart: on-failure
    volumes:
      - "./:/hostdata"      
    command: ["sleep", "infinity"]      
#
# CentOS8 - SECOND
#  
  centos2:
    image: centos:8.4.2105
    networks:
      net1:
        priority: 10
        ipv4_address: "172.44.4.3"
      net2:
        priority: 0
      net3:
        priority: 0
    hostname: centos2
    container_name: centos2-devesp
    privileged: true
    entrypoint: ["/usr/sbin/init"]    
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 

#
# U22 - FIRST
#  
  ubuntu1:
    image: ubuntu:22.04
    networks:   
      net1:
        priority: 0   
      net2:
        priority: 30
        ipv4_address: "172.45.4.3"           
      net3:
        priority: 0          
    hostname: ubuntu1
    container_name: ubuntu1-devesp
    privileged: true 
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"] 

#
# U22 - SECOND
#  
  ubuntu2:
    image: ubuntu:22.04
    networks:   
      net1:
        priority: 0   
      net2:
        priority: 30
        ipv4_address: "172.45.4.4"           
      net3:
        priority: 0   
    hostname: ubuntu2
    container_name: ubuntu2-devesp
    privileged: true 
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"]

#
# debian - THIRD
#  
  debian1:
    image: debian:stable-slim
    networks:   
      net1:
        priority: 0
      net2:
        priority: 0        
      net3:
        priority: 30
        ipv4_address: "172.46.4.2"           
    hostname: debian1
    container_name: debian1-devesp
    privileged: true 
    restart: on-failure
    volumes:
      - "./:/hostdata"    
    command: ["sleep", "infinity"]

networks:
  net1:
    ipam: 
      driver: default
      config:
        - subnet: "172.44.0.0/16"
          ip_range: "172.44.4.0/16"
  net2:
    ipam: 
      driver: default
      config:
        - subnet: "172.45.0.0/16"
          ip_range: "172.45.4.0/16"
  net3:
    ipam: 
      driver: default
      config:
        - subnet: "172.46.0.0/16" 
          ip_range: "172.46.4.0/16"